name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ git
        
    - name: Build and test
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTS=ON
        cmake --build .
        ./tests/tests
