name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ lcov gcovr
        
    - name: Configure and Build
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
        cmake --build . --config Debug
        
        
    - name: Run tests and coverage
      run: |
        cd build
        ./tests
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info
        
    - name: Upload to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: build/coverage.info
