name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake lcov gcovr

    - name: Configure and Build
      run: |
        cmake -B build -DBUILD_TESTS=ON -DCOVERAGE=ON
        cmake --build build

    - name: Run tests
      working-directory: ./build
      run: |
        ctest --output-on-failure
        ./banking_tests

    - name: Generate coverage
      run: |
        lcov --capture --directory ./build --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./build/coverage.info
